/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
/**
 *
 * @author horacio
 * 
 */
public class Calculator extends javax.swing.JFrame {
    int number1 = 0, number2 = 0;
    char oper;
    
    
    
    public Calculator() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_input = new javax.swing.JLabel();
        txt_output = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_equal = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        btn_power = new javax.swing.JButton();
        btn_percent = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_restar = new javax.swing.JButton();
        btn_sumar = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        btn_float = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();

        jButton6.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(55, 62, 71));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        jButton6.setText("C");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(340, 540));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 253, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input.setFont(new java.awt.Font("SauceCodePro NF", 1, 18)); // NOI18N
        txt_input.setForeground(new java.awt.Color(55, 62, 71));
        txt_input.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txt_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, 316, 37));

        txt_output.setFont(new java.awt.Font("Source Code Pro Black", 0, 48)); // NOI18N
        txt_output.setForeground(new java.awt.Color(55, 62, 71));
        txt_output.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txt_output, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 316, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_equal.setFont(new java.awt.Font("RobotoMono Nerd Font SmBd", 0, 30)); // NOI18N
        btn_equal.setForeground(new java.awt.Color(255, 255, 255));
        btn_equal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/equal.png"))); // NOI18N
        btn_equal.setText("=");
        btn_equal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_equal.setFocusPainted(false);
        btn_equal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_equal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_equal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalActionPerformed(evt);
            }
        });
        jPanel2.add(btn_equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 50, 50));

        num9.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num9.setForeground(new java.awt.Color(55, 62, 71));
        num9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num9.setText("9");
        num9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num9.setFocusPainted(false);
        num9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel2.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 50, 50));

        btn_power.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_power.setForeground(new java.awt.Color(55, 62, 71));
        btn_power.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_power.setText("^");
        btn_power.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_power.setFocusPainted(false);
        btn_power.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_power.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_power.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_powerActionPerformed(evt);
            }
        });
        jPanel2.add(btn_power, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 50));

        btn_percent.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_percent.setForeground(new java.awt.Color(55, 62, 71));
        btn_percent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_percent.setText("%");
        btn_percent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_percent.setFocusPainted(false);
        btn_percent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_percent.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_percent.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_percentActionPerformed(evt);
            }
        });
        jPanel2.add(btn_percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 50, 50));

        btn_dividir.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_dividir.setForeground(new java.awt.Color(55, 62, 71));
        btn_dividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_dividir.setText("÷");
        btn_dividir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_dividir.setFocusPainted(false);
        btn_dividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dividir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_dividir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 50, 50));

        btn_multiplicar.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_multiplicar.setForeground(new java.awt.Color(55, 62, 71));
        btn_multiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_multiplicar.setText("x");
        btn_multiplicar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_multiplicar.setFocusPainted(false);
        btn_multiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multiplicar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_multiplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 50, 50));

        btn_restar.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_restar.setForeground(new java.awt.Color(55, 62, 71));
        btn_restar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_restar.setText("-");
        btn_restar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_restar.setFocusPainted(false);
        btn_restar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_restar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_restar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 50, 50));

        btn_sumar.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_sumar.setForeground(new java.awt.Color(55, 62, 71));
        btn_sumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_sumar.setText("+");
        btn_sumar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_sumar.setFocusPainted(false);
        btn_sumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sumar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_sumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 50));

        btn_c.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_c.setForeground(new java.awt.Color(55, 62, 71));
        btn_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_c.setText("C");
        btn_c.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_c.setFocusPainted(false);
        btn_c.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_c.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_c.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });
        jPanel2.add(btn_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));

        num7.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num7.setForeground(new java.awt.Color(55, 62, 71));
        num7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num7.setText("7");
        num7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num7.setFocusPainted(false);
        num7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        jPanel2.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 50));

        num8.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num8.setForeground(new java.awt.Color(55, 62, 71));
        num8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num8.setText("8");
        num8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num8.setFocusPainted(false);
        num8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel2.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, 50));

        jButton13.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(55, 62, 71));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        jButton13.setText("C");
        jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton13.setFocusPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 50, 50));

        jButton14.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(55, 62, 71));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        jButton14.setText("C");
        jButton14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton14.setFocusPainted(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 50));

        jButton15.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(55, 62, 71));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        jButton15.setText("C");
        jButton15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton15.setFocusPainted(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, 50));

        num4.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num4.setForeground(new java.awt.Color(55, 62, 71));
        num4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num4.setText("4");
        num4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num4.setFocusPainted(false);
        num4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel2.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 50, 50));

        num5.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num5.setForeground(new java.awt.Color(55, 62, 71));
        num5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num5.setText("5");
        num5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num5.setFocusPainted(false);
        num5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel2.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 50, 50));

        num6.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num6.setForeground(new java.awt.Color(55, 62, 71));
        num6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num6.setText("6");
        num6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num6.setFocusPainted(false);
        num6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        jPanel2.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 50, 50));

        num3.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num3.setForeground(new java.awt.Color(55, 62, 71));
        num3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num3.setText("3");
        num3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num3.setFocusPainted(false);
        num3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel2.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 50, 50));

        num2.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num2.setForeground(new java.awt.Color(55, 62, 71));
        num2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num2.setText("2");
        num2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num2.setFocusPainted(false);
        num2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel2.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 50, 50));

        num1.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num1.setForeground(new java.awt.Color(55, 62, 71));
        num1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num1.setText("1");
        num1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num1.setFocusPainted(false);
        num1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel2.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, 50));

        num0.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        num0.setForeground(new java.awt.Color(55, 62, 71));
        num0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        num0.setText("0");
        num0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num0.setFocusPainted(false);
        num0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        num0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        jPanel2.add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 50));

        btn_float.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_float.setForeground(new java.awt.Color(55, 62, 71));
        btn_float.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/02.png"))); // NOI18N
        btn_float.setText(".");
        btn_float.setToolTipText("");
        btn_float.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_float.setFocusPainted(false);
        btn_float.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_float.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01.png"))); // NOI18N
        btn_float.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/01_event.png"))); // NOI18N
        btn_float.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_floatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_float, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 50, 50));

        btn_del.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        btn_del.setForeground(new java.awt.Color(55, 62, 71));
        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn_delete_01.png"))); // NOI18N
        btn_del.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_del.setFocusPainted(false);
        btn_del.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_del.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn_delete_01_event.png"))); // NOI18N
        btn_del.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn/btn_delete_01_event.png"))); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel2.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 340, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_powerActionPerformed
        addNumber("^");
    }//GEN-LAST:event_btn_powerActionPerformed

    private void btn_percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_percentActionPerformed
        addNumber("%");
    }//GEN-LAST:event_btn_percentActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        String texto = txt_input.getText().substring(0, txt_input.getText().length() - 1);
        txt_input.setText(texto);
        //btn_equal.doClick();
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txt_input.setText("");
        txt_output.setText("");
    }//GEN-LAST:event_btn_cActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        addNumber("2");
        //btn_equal.doClick();
    }//GEN-LAST:event_num2ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        addNumber("7");
        //btn_equal.doClick();
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        addNumber("8");
        //btn_equal.doClick();
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        addNumber("9");
        //btn_equal.doClick();
    }//GEN-LAST:event_num9ActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        addNumber("x");
        String num1 = txt_input.getText();
        number1 = Integer.parseInt(num1);
        oper = '*';
        txt_input.setText("");
        System.out.println(num1);
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarActionPerformed
        String num1 = txt_input.getText();
        number1 = Integer.parseInt(num1);
        oper = '-';
        txt_input.setText("");
        System.out.println(num1);
    }//GEN-LAST:event_btn_restarActionPerformed

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
       //addNumber("+");
       String num1 = txt_input.getText();
       number1 = Integer.parseInt(num1);
       oper = '+';
       txt_input.setText("");
       System.out.println(num1);
    }//GEN-LAST:event_btn_sumarActionPerformed

    private void btn_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalActionPerformed
        String num2 = txt_input.getText();
        number2 = Integer.parseInt(num2);
        txt_input.setText("");
        System.out.println(num2);
    	/*
        try {
            String resultado = se.eval(txt_input.getText()).toString();
            txt_output.setText(resultado);
        } catch (Exception e){
            System.out.println(e);
        }*/
    }//GEN-LAST:event_btn_equalActionPerformed

    private void btn_floatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_floatActionPerformed
        addNumber(".");
        //btn_equal.doClick();
    }//GEN-LAST:event_btn_floatActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
       addNumber("0");
       //btn_equal.doClick();
    }//GEN-LAST:event_num0ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        addNumber("1");
        //btn_equal.doClick();
    }//GEN-LAST:event_num1ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        addNumber("3");
        //btn_equal.doClick();
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        addNumber("4");
        //btn_equal.doClick();
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        addNumber("5");
        //btn_equal.doClick();
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        addNumber("6");
        //btn_equal.doClick();
    }//GEN-LAST:event_num6ActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
       addNumber("÷");
       String num1 = txt_input.getText();
       number1 = Integer.parseInt(num1);
       oper = '/';
       txt_input.setText("");
       System.out.println(num1);
    }//GEN-LAST:event_btn_dividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    public void addNumber(String digit){
        txt_input.setText(txt_input.getText() + digit);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_float;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_percent;
    private javax.swing.JButton btn_power;
    private javax.swing.JButton btn_restar;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JLabel txt_input;
    private javax.swing.JLabel txt_output;
    // End of variables declaration//GEN-END:variables
}
